import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/Component/Navber";
import Footer from "@/Component/Footer";
import { Toaster } from "react-hot-toast";
import Authprovider from "./Authentication/Authprovider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Authprovider>
          <Navbar />
          {children}
          <Footer />
          <Toaster />
        </Authprovider>
      </body>
    </html>
  );
}
